apiVersion: apps.k8smgmt.io/v3
kind: Workload
metadata:
  name: krishna-feb2new-test-2
  project: defaultproject
spec:
  artifact:
    artifact:
      paths:
      - name: file://artifacts/before-opa/before-opa.yaml
    type: Yaml
  namespace: feb2-ns
  placement:
    selector: rafay.dev/clusterName=krishna-feb2-test
  version: krishna-feb2new-test-2-v2-202604200646300000
