apiVersion: apps.k8smgmt.io/v3
kind: Workload
metadata:
  name: krishna-test-mar61
  project: defaultproject
spec:
  artifact:
    artifact: {}
    type: Helm
  namespace: string
  placement:
    selector: rafay.dev/clusterName=string
