apiVersion: apps.k8smgmt.io/v3
kind: Workload
metadata:
  name: krishna-test-v3-new
  project: defaultproject
spec:
  artifact:
    artifact:
      catalog: default-helm
      chartName: simple-nginx
      chartVersion: 1.1.1
      valuesPaths:
      - name: file://values.yaml
    options:
      maxHistory: 10
      timeout: 5m0s
    type: Helm
  namespace: krish-ns-feb19
  placement:
    selector: rafay.dev/clusterName=giri-feb19-qc
