apiVersion: apps.k8smgmt.io/v3
kind: Workload
metadata:
  name: test-11
  project: defaultproject
spec:
  artifact:
    artifact:
      catalog: default-helm
      chartName: simple-nginx
      chartVersion: 1.1.1
    type: Helm
  namespace: jul22-ns
