apiVersion: apps.k8smgmt.io/v3
kind: Workload
metadata:
  name: test-multi-files-1-git
  project: defaultproject
spec:
  artifact:
    artifact:
      chartName: some-chart
      chartVersion: 1.2.3
      repository: default-stable-helm
      valuesRef:
        repository: test-platform
        revision: main
        valuesPaths:
        - name: muti-file-path-test/values-prod.yaml
    options:
      maxHistory: 10
      timeout: 5m0s
    type: Helm
  namespace: apr7-ns
  placement:
    selector: rafay.dev/clusterName=krishna-pipeline-test
  version: test-multi-files-1-git-v4-202604151031120000
