apiVersion: apps.k8smgmt.io/v3
kind: Workload
metadata:
  name: test-multi-files
  project: defaultproject
spec:
  artifact:
    artifact:
      chartPath: {}
      repository: test-platform
      revision: main
      valuesPaths:
      - {}
      valuesRef:
        repository: test-platform
        revision: muti-file-path-test/values-dev.yaml
        valuesPaths:
        - name: muti-file-path-test/values-pre-prod.yaml
        - name: muti-file-path-test/values-prod.yaml
    options:
      maxHistory: 10
      timeout: 5m0s
    type: Helm
  namespace: apr7-ns
  placement:
    selector: rafay.dev/clusterName=krishna-pipeline-test
  version: test-multi-files-v1-202604150721330000
