apiVersion: apps.k8smgmt.io/v3
kind: Workload
metadata:
  name: tftestworkload1-new
  project: defaultproject
spec:
  artifact:
    artifact: {}
    options: {}
    type: Yaml
  namespace: ns-1
  placement:
    selector: rafay.dev/clusterName=krishna-oct28
